language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
  - rbx

gemfile:
 - Gemfile
 - Gemfile.v0.12

branches:
  only:
    - master

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: rbx
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0
      gemfile: Gemfile
